/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmi;

import bmiDao.tinhBMI;

/**
 *
 * @author lam08
 */
public class Gui_MnBMI extends javax.swing.JFrame {

    /**
     * Creates new form Gui_MnBMI
     */
    public Gui_MnBMI() {
        initComponents();
        this.setTitle("Tính BMI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxt1 = new javax.swing.JTextField();
        jlb1 = new javax.swing.JLabel();
        jtxt2 = new javax.swing.JTextField();
        jlb2 = new javax.swing.JLabel();
        jbtn1 = new javax.swing.JButton();
        jlbKQ = new javax.swing.JLabel();
        jlb3 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jlbLuuY = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 112, -1));

        jlb1.setText("nhập chiều cao");
        getContentPane().add(jlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        getContentPane().add(jtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 112, -1));

        jlb2.setText("nhập cân nặng");
        getContentPane().add(jlb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        jbtn1.setBackground(new java.awt.Color(204, 255, 255));
        jbtn1.setText("Tính BMI");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 139, 96, -1));
        getContentPane().add(jlbKQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 173, 133, 29));

        jlb3.setText("Kết quả:");
        getContentPane().add(jlb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 173, -1, 29));

        jlb4.setText("Lưu ý: (*)");
        getContentPane().add(jlb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 234, 70, -1));
        getContentPane().add(jlbLuuY, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 440, 26));

        jLabel1.setText("(m)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel2.setText("(kg)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt1ActionPerformed
        // TODO add your handling code here:
         
         
    }//GEN-LAST:event_jtxt1ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
             
        // TODO add your handling code here:
        
        tinhBMI t = new tinhBMI();
        
//        Double bmi = t.tinhBMIs(Double.valueOf(jtxt2), Double.valueOf(jtxt1));

//        
        Object btn = evt.getSource();
        
        if(btn.equals(jbtn1)){
           jlbKQ.setText(String.valueOf(t.tinhBMIs(Double.valueOf(jtxt1.getText()), Double.valueOf(jtxt2.getText()))));
           
           Double bmi = t.tinhBMIs(Double.valueOf(jtxt1.getText()), Double.valueOf(jtxt2.getText()));
           if(bmi < 18.5){
               
                jlbLuuY.setText("Thiếu cân, cần điều chỉnh lại chế độ ăn uống");
             } else if(bmi >= 18.5 && bmi <= 22.9){
                 
                jlbLuuY.setText("Chỉ số BMI này chứng tỏ bạn đang ở tình trạng cân đối Bình thường");
             } else if (bmi >= 23 && bmi <=24.9) {
                 
                 jlbLuuY.setText("Thừa cân, cần điều chỉnh lại chế độ ăn uống");        
             } else if (bmi >= 25) {
                 jlbLuuY.setText("Béo phì, cần điều chỉnh lại chế độ ăn uống");  
             }
             else {
               jlbLuuY.setText("Hãy nhập liệu đúng");
             }
        }
        
    }//GEN-LAST:event_jbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_MnBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_MnBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_MnBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_MnBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_MnBMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtn1;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JLabel jlb4;
    private javax.swing.JLabel jlbKQ;
    private javax.swing.JLabel jlbLuuY;
    private javax.swing.JTextField jtxt1;
    private javax.swing.JTextField jtxt2;
    // End of variables declaration//GEN-END:variables
}
